### ISSUE TITLE
Encoding problem

### ISSUE THREAD

**Issue by tomkri3** [wooio/htmltopdf-java#12]
Hello,
I really like your library is really easy to use! I am from Czech Republic. So we need encoding to corretly display our language.
But i encoutered a problem. When i am running htmltopdf-java like this

```
public static void main(String[] args) throws IOException {
    String inputFile = "/tmp/a.html";
    String outputFile = "/tmp/out.pdf";
    String inputContent = String.join("", Files.readAllLines(Paths.get(inputFile)));

    HtmlToPdf.create()
            .object(HtmlToPdfObject.forHtml(inputContent))
            .convert(outputFile);

    System.out.println("Done!");
}
```
Then everything is ok. But when i am using htmltopdf-java inside our project. There is for me unknow issue. When i am running on same input file. Its not stored in UTF-8 encoding. And i have no idea why. In our application we use code like this

```
    public void convertHtml() {
        try {
            reentrantLock.lock();
            byte[] bytes;
            try {
                bytes = Files.readAllBytes(Paths.get("/tmp/a.html"));
            } catch (IOException e) {
                throw new UncheckedIOException(e);
            }

            String fileHtml = new String(bytes, Charset.forName("UTF-8"));
            HtmlToPdf.create()
                    .object(HtmlToPdfObject.forHtml(fileHtml))
                    .convert("/tmp/out.pdf");
        } finally {
            reentrantLock.unlock();
        }
    }
```
content of **a.html**

```
<!DOCTYPE html>
<?xml version='1.0' encoding='UTF-8'?>
<html>
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/
  </head>
   <body>
     <p>Příliš žluťoučký kůň úpěl ďábelské ódy</p>
   </body>
<html>

```
Any help would be appreciated! Just for info. Both usages is in same maven module. Difference is only starting of app.
[out.pdf](https://github.com/wooio/htmltopdf-java/files/2400922/out.pdf)

**Comment by benbarkay** [comment]
I could not reproduce what you are experiencing. Attached is the output file that I get:
[out.pdf](https://github.com/wooio/htmltopdf-java/files/2408059/out.pdf)

Perhaps the file isn't saved as UTF-8, and the characters aren't encoded correctly in the conversion in this line:
```java
            String fileHtml = new String(bytes, Charset.forName("UTF-8"));
```
(which is a behavioral difference between the two snippets)

**Comment by Victornade** [comment]
Hello,
I have a similar problem with my code.

My String is in UTF-8 and seems to be converted by Java in ANSI. However I could convert it back to UTF-8 with your line above. If y a store it as a file.html it works well but if I convert it in PDF and store it in a file.pdf the accents are gone again...

Could you please tell me wich Encoding type you're code is waiting ?

Thanks !

PS : Thank you for your code, really easy to use and implement !


`
        String etatActuelTemp = "éçùà";
        String etatActuel;
        try{
            File tempFil = File.createTempFile("testing", ".html");
            FileUtils.writeStringToFile(tempFil, etatActuelTemp);  //ACCENT are gone
        }
        catch (java.io.IOException e){
            //TODO
            return null;
        }
        try {
            etatActuel = new String(etatActuelTemp.getBytes(), "UTF-8");

        }
        catch(java.io.UnsupportedEncodingException e){
            return null;
        }
        try{
            File tempFil = File.createTempFile("testing", ".html"); 
            FileUtils.writeStringToFile(tempFil, etatActuel);//Accent are back

        }
        catch (java.io.IOException e){
            //TODO
            return null;
        }


        HtmlToPdf htmlToPdf = HtmlToPdf.create()
                .object(HtmlToPdfObject.forHtml(etatActuel));

        try (InputStream in = htmlToPdf.convert()) {
            // "in" has PDF bytes loaded
            
            //Upload file into temp directory (On window : C:\Program...\apache..\temp\
            //Please check permission to avoid IOException error
            File tempFile = File.createTempFile("test", ".pdf"); //ACCENT ARE GONE AGAIN
            //Mark file to delete on application exit
            tempFile.deleteOnExit();
            //copy content of buffer into file
            FileOutputStream fos = new FileOutputStream(tempFile);
            byte[] buffer = new byte[8 * 1024];
            int bytesRead;
            while ((bytesRead = in.read(buffer)) != -1) {
                fos.write(buffer, 0, bytesRead);
            }

            return in;
        } catch (java.io.IOException e){
            //TODO
            return null;
        }
`

**Comment by benbarkay** [comment]
@Victornade 
Try using this instead:
```java
"<html><head><meta charset=\"UTF-8\" /></head><body>éçùà</body></html>"
```
I was able to produce a PDF file which kept the charset this way.
