### ISSUE TITLE
Zoom

### ISSUE THREAD

**Issue by schmidii** [wooio/htmltopdf-java#17]
Hello,
when I am creating pdf's with the library the content is much smaller as if I just create it with wkhtmltopdf. I experimented with diffrent setting mechanisms and discovered that **zoom** has no affect at all... My code looks as follows:
```    
HtmlToPdf.create()
        .zoom(10)
        .pageSize(PdfPageSize.A4)
        .object(HtmlToPdfObject.forHtml(html))
        .convert(destination);
```
Every value submitted to zoom creates the same output.

**Comment by benbarkay** [comment]
Seems to be related to https://bugs.launchpad.net/ubuntu/+source/wkhtmltopdf/+bug/1391456
Ill

**Comment by benbarkay** [comment]
It appears that the global settings don't have a `zoom` property. Instead you should try using `HtmlToPdfObject#zoomFactor`, like so:

```java
HtmlToPdf.create()
        .pageSize(PdfPageSize.A4)
        .object(HtmlToPdfObject.forHtml(html)
                        .zoomFactor(10))
        .convert(destination);
```

Let me know if this works out for you

**Comment by schmidii** [comment]
Thank you, for the answer. This actually solves the problem. :)

Only for completeness, I am working on macOs 10.14.2, and with zoomFactor(3.1f) the resulting pdf looks like converted directly with wkhtmltopdf.

**Comment by Developer74** [comment]
> It appears that the global settings don't have `zoom` as a setting property. Try using `HtmlToPdfObject#zoomFactor` instead, like so:
> 
> ```java
> HtmlToPdf.create()
>         .pageSize(PdfPageSize.A4)
>         .object(HtmlToPdfObject.forHtml(html)
>                         .zoomFactor(10))
>         .convert(destination);
> ```
> 
> Let me know if this works out for you.

Hi, can you please say solution to add custom pagesize and add headers and footer to it
