### ISSUE TITLE
suggestion: add support for CompletableFuture

### ISSUE THREAD

**Issue by keisar** [wooio/htmltopdf-java#6]
so you'd be able to do:
```
CompletableFuture<InputStream> future = HtmlToPdf.createAsync()
                .object(HtmlToPdfObject.forUrl("http://amazon.com"))
                .convert(); // can also be .convertAsync()
future.thenApply(is -> handleInputStreamAsync....);
```
I think this is something that is lacking currently from other frameworks and shouldn't be hard to implement (I can give it a go and send a PR if you'd like)

**Comment by benbarkay** [comment]
You could implement such behavior in multiple fashions which don't require adding the functionality to the library, such as with `CompletableFuture` for instance:

```java
HtmlToPdf htmlToPdf = HtmlToPdf.create()
        .object(HtmlToPdfObject.forUrl("http://amazon.com"));
    
    CompletableFuture.supplyAsync(htmlToPdf::convert)
        .thenApply(is -> {
    // ...
});
```
