### ISSUE TITLE
Calling convert() second time freezes

### ISSUE THREAD

**Issue by lgabeskiria** [wooio/htmltopdf-java#8]
```
private ResponseEntity<byte[]> toPdf(String name, Map model, PdfOrientation pdfOrientation) {
        String html = toHtml(name, model);
        try (InputStream pdfIn =  HtmlToPdf.create().object(HtmlToPdfObject.forHtml(html)).convert()) {
            byte[] targetArray = new byte[pdfIn.available()];
            pdfIn.read(targetArray);
            return ResponseEntity.ok(targetArray);
        } catch (HtmlToPdfException | IOException e) {
            e.printStackTrace();
        }
        return ResponseEntity.noContent().build();
    }
```

**Comment by lgabeskiria** [comment]
Yes

**Comment by benbarkay** [comment]
I am unable to reproduce this myself, and your snippet depends on the rest of the code of your project. What I can say, however, is that the way that you read `pdfIn` is fishy -- I suggest that you should look into using Spring's `InputStreamResource` and returning it in your `ResponseEntity` instead.

If you could reproduce this with a snippet that people not involved in your project could run then that would be great, however I also suspect that simply using `InputStreamResource` would work out for you :)

**Comment by lgabeskiria** [comment]
Not working :(
When sending first request everything is ok, but further requests just return 504 result.
I had same situation when working with .netcore lib called DinkToPdf. However they provide SyncronizedConverter that should be used in multithreaded applications. I think we have same problem here

**Comment by benbarkay** [comment]
I found another issue with concurrency. Maybe if I resolve this, then that would resolve what you are experiencing. I'm going to release 1.0.3 in a couple of hours probably.

**Comment by benbarkay** [comment]
It was worse than I thought -- Not only does wkhtmltopdf not support concurrency, it also does not support making calls from any thread that wasn't the threat that initialized it. It appears to be a common pain point for plenty other projects as well.

So it's going to take a little longer, but I'm working on a fix.
